// 星火图志数据文件 —— 人物与文物
// id 必须与 final/ 和 inputs/inputsF/ 中的文件名前缀一致
// type: "person"（历史人物）| "artifact"（历史文物/文献）
//
// ⚠️ 史实审核提示：以下生平与文物说明为团队整理的初稿，
//    正式发布前须提交校史专家审核纠偏（见立项书风险对策）。
//    标注"待考证"的条目尤其需要核实。

const fs = require("fs");
const path = require("path");

// 构建时探测修复图扩展名（final/{id}.png 或 final/{id}.jpg）
function restoredImage(id) {
  for (const ext of ["png", "jpg"]) {
    if (fs.existsSync(path.join(__dirname, "..", "final", `${id}.${ext}`))) {
      return `/final/${id}.${ext}`;
    }
  }
  return null;
}

module.exports = [
  // ============ 历史人物 ============
  {
    id: "dzx",
    name: "邓中夏",
    type: "person",
    birth: "1894",
    death: "1933",
    summary: "中国共产党早期领导人、工人运动杰出领袖，中国社会主义青年团创建时期的重要领导人，出席团二大。",
    biography: "邓中夏（1894-1933），湖南宜章人。中国共产党早期领导人之一，中国工人运动的杰出领袖。他是中国社会主义青年团创建时期的重要领导人，1923年出席在梅庵召开的团二大。1933年9月牺牲于南京雨花台。（生平详情待校史专家审核补充）",
    period: "团二大",
    importance: 5,
    tags: ["团二大", "工运领袖"],
  },
  {
    id: "mzd",
    name: "毛泽东",
    type: "person",
    birth: "1893",
    death: "1976",
    summary: "1923年8月以中共中央代表身份出席在梅庵召开的团二大并作报告，这是毛泽东同志唯一一次全程参与的团的全国代表大会。",
    biography: "1923年8月20日至25日，中国社会主义青年团第二次全国代表大会在梅庵召开。毛泽东同志以中共中央代表身份全程参会并作报告。据南京市委党史工办与东南大学的联合研究成果，这是毛泽东同志唯一一次全程参与的团的全国代表大会，在共青团史和中国青年运动史上具有极高分量。（详情待校史专家审核补充）",
    period: "团二大",
    importance: 5,
    tags: ["中共中央代表", "团二大"],
  },
  {
    id: "zqb",
    name: "瞿秋白",
    type: "person",
    birth: "1899",
    death: "1935",
    summary: "中国共产党早期主要领导人、马克思主义理论家，与青年团工作关系密切。",
    biography: "瞿秋白（1899-1935），江苏常州人。中国共产党早期主要领导人之一，杰出的马克思主义理论家和宣传家。1935年英勇就义。（与团二大及梅庵的具体关联待校史专家审核补充）",
    period: "团二大",
    importance: 5,
    tags: ["理论家"],
  },
  {
    id: "lyn",
    name: "林育南",
    type: "person",
    birth: "1898",
    death: "1931",
    summary: "中国工人运动和青年运动早期领导人，出席团二大。",
    biography: "林育南（1898-1931），湖北黄冈人。中国工人运动和青年运动的早期领导人，1923年出席在梅庵召开的团二大。1931年牺牲。（生平详情待校史专家审核补充）",
    period: "团二大",
    importance: 4,
    tags: ["团二大", "工运领袖"],
  },
  {
    id: "hrk",
    name: "黄日葵",
    type: "person",
    birth: "1898",
    death: "1930",
    summary: "广西最早的马克思主义传播者之一，五四运动骨干，中国社会主义青年团早期团员。",
    biography: "黄日葵（1898-1930），广西桂平人。五四运动骨干，广西最早的马克思主义传播者之一，中国社会主义青年团早期团员。（生平详情待校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["五四骨干"],
  },
  {
    id: "sct",
    name: "施存统",
    type: "person",
    birth: "1899",
    death: "1970",
    summary: "中国社会主义青年团第一任中央书记。",
    biography: "施存统（1899-1970），浙江金华人。中国社会主义青年团主要创始人之一，1922年在团一大上当选为团中央第一任书记。（生平详情待校史专家审核补充）",
    period: "建团初期",
    importance: 4,
    tags: ["首任团中央书记"],
  },
  {
    id: "zxn",
    name: "赵醒侬",
    type: "person",
    birth: "1899",
    death: "1926",
    summary: "江西地方党团组织的主要创始人，青年运动先驱。",
    biography: "赵醒侬（1899-1926），江西南丰人。江西地方党团组织的主要创始人，江西青年运动先驱。1926年牺牲。（生平详情待校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["江西党团创始人"],
  },
  {
    id: "lrj",
    name: "刘仁静",
    type: "person",
    birth: "1902",
    death: "1987",
    summary: "中共一大最年轻的代表，中国社会主义青年团早期领导人，出席团二大。",
    biography: "刘仁静（1902-1987），湖北应城人。中共一大最年轻的代表，中国社会主义青年团早期领导人，1923年出席在梅庵召开的团二大。（生平详情待校史专家审核补充）",
    period: "团二大",
    importance: 4,
    tags: ["中共一大代表", "团二大"],
  },
  {
    id: "lyy",
    name: "林育英",
    type: "person",
    birth: "1897",
    death: "1942",
    summary: "化名张浩，中国工人运动早期领导人，林育南堂兄。",
    biography: "林育英（1897-1942），化名张浩，湖北黄冈人。中国工人运动早期领导人，林育南堂兄。（生平详情待校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["工运领袖"],
  },
  {
    id: "yxj",
    name: "杨贤江",
    type: "person",
    birth: "1895",
    death: "1931",
    summary: "中国最早的马克思主义教育理论家之一，青年运动的重要领导人。",
    biography: "杨贤江（1895-1931），浙江余姚人。中国最早的马克思主义教育理论家之一，青年运动的重要领导人，长期从事青年教育与进步刊物编辑工作。（生平详情待校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["教育理论家"],
  },
  {
    id: "xyd",
    name: "谢远定",
    type: "person",
    birth: "1898",
    death: "",
    summary: "中国社会主义青年团早期领导人之一。",
    biography: "谢远定（1898-？），中国社会主义青年团早期领导人之一。（生卒年及生平详情待考证，请校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["建团初期"],
  },
  {
    id: "hy",
    name: "侯曜",
    type: "person",
    birth: "1903",
    death: "1942",
    summary: "毕业于东南大学，中国早期电影编剧、导演。",
    biography: "侯曜（1903-1942），广东番禺人，毕业于东南大学。中国早期电影编剧、导演，是中国电影事业的先驱者之一。（与梅庵团史的具体关联待校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["东大学子", "电影先驱"],
  },
  {
    id: "wxy",
    name: "宛希俨",
    type: "person",
    birth: "1903",
    death: "1928",
    summary: "就读于东南大学，中共早期党员，南京地区青年运动骨干。",
    biography: "宛希俨（1903-1928），湖北黄梅人，就读于东南大学，中共早期党员，南京地区青年运动的骨干力量。1928年牺牲。（生平详情待校史专家审核补充）",
    period: "建团初期",
    importance: 3,
    tags: ["东大学子", "青运骨干"],
  },

  // ============ 历史文物 / 文献 ============
  {
    id: "snzg",
    name: "《少年中国》杂志",
    type: "artifact",
    birth: "",
    death: "",
    summary: "少年中国学会会刊，1919年创刊，传播新思想新文化的重要阵地。",
    biography: "《少年中国》月刊是少年中国学会的会刊，1919年创刊，是五四时期传播新思想、新文化的重要阵地，对进步青年影响深远。（详情待校史专家审核补充）",
    period: "建团初期",
    importance: 2,
    tags: ["进步刊物"],
  },
  {
    id: "snsj",
    name: "《少年世界》杂志",
    type: "artifact",
    birth: "",
    death: "",
    summary: "少年中国学会南京会员创办的刊物，1920年创刊。",
    biography: "《少年世界》月刊由少年中国学会南京地区会员主办，1920年创刊，注重社会实际问题的调查与研究。（详情待校史专家审核补充）",
    period: "建团初期",
    importance: 2,
    tags: ["进步刊物"],
  },
  {
    id: "dnzp",
    name: "《东南评论社简则》原稿",
    type: "artifact",
    birth: "",
    death: "",
    summary: "反映东南大学早期进步社团活动的珍贵文献原稿。",
    biography: "《东南评（平）论社简则》原稿，是反映东南大学早期进步社团活动的珍贵文献。（详情待校史专家审核补充）",
    period: "建团初期",
    importance: 2,
    tags: ["文献原稿"],
  },
  {
    id: "njshkx",
    name: "《南京社会科学研究会》史料",
    type: "artifact",
    birth: "",
    death: "",
    summary: "南京地区早期传播马克思主义的进步团体相关史料。",
    biography: "南京社会科学研究会是南京地区早期研究和传播马克思主义的进步团体，此为相关珍贵史料。（详情待校史专家审核补充）",
    period: "建团初期",
    importance: 2,
    tags: ["进步团体"],
  },
  {
    id: "mgsx",
    name: "两江师范学堂木工实习影像",
    type: "artifact",
    birth: "",
    death: "",
    summary: "两江师范学堂（东南大学前身）学生进行木工实习的历史影像。",
    biography: "两江师范学堂是东南大学的前身。此照片记录了学堂学生进行木工实习的场景，反映了学堂重视实科教育的办学传统。（详情待校史专家审核补充）",
    period: "学堂时期",
    importance: 2,
    tags: ["学堂时期", "历史影像"],
  },
  {
    id: "dxsw",
    name: "《悼柳生文》",
    type: "artifact",
    birth: "",
    death: "",
    summary: "纪念性文献手稿。",
    biography: "《悼柳生文》手稿。（文献背景与作者信息待考证，请校史专家审核补充）",
    period: "建团初期",
    importance: 2,
    tags: ["文献手稿"],
  },
  {
    id: "dy",
    name: "《古道可风之清道人》",
    type: "artifact",
    birth: "",
    death: "",
    summary: "赵正平《四十年来师友感怀录》中追忆李瑞清（号清道人）的篇章，梅庵之名即源于李瑞清。",
    biography: "赵正平著《四十年来师友感怀录·古道可风之清道人》，追忆两江师范学堂监督李瑞清。李瑞清号梅庵、晚号清道人，主持两江师范学堂期间倡导实科教育。校园内的梅庵建筑即为纪念他而得名。（详情待校史专家审核补充）",
    period: "学堂时期",
    importance: 2,
    tags: ["学堂时期", "梅庵渊源"],
  },
].map((c) => ({
  ...c,
  image: restoredImage(c.id),
  original: `/inputs/inputsF/${c.id}.jpg`,
}));
