// 人物数据文件
// TODO: 请团队成员将每个条目中的 name、birth、death、summary、biography 替换为真实历史资料
// id 必须与 final/ 和 inputs/inputsF/ 中的文件名前缀一致

const fs = require("fs");
const path = require("path");

// 构建时探测修复图扩展名（final/{id}.png 或 final/{id}.jpg）
function restoredImage(id) {
  for (const ext of ["png", "jpg"]) {
    if (fs.existsSync(path.join(__dirname, "..", "final", `${id}.${ext}`))) {
      return `/final/${id}.${ext}`;
    }
  }
  return null;
}

module.exports = [
  {
    id: "dzx",
    name: "邓中夏",
    birth: "1894",
    death: "1933",
    summary: "中国社会主义青年团早期领导人，团二大代表。",
    biography: "（待补充：邓中夏同志生平简介。请根据校史馆资料和历史文献填写。）",
    period: "建团初期",
    importance: 5,
    tags: ["团二大代表", "工运领袖"],
  },
  {
    id: "mzd",
    name: "毛泽东",
    birth: "1893",
    death: "1976",
    summary: "1923年以中共中央代表身份出席团二大并作报告，这是毛泽东同志唯一一次全程参与的团的全国代表大会。",
    biography: "（待补充：毛泽东同志与梅庵、团二大的历史关联。）",
    period: "团二大",
    importance: 5,
    tags: ["中共中央代表", "团二大"],
  },
  {
    id: "zqb",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "lyn",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "hrk",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "sct",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "zxn",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "lrj",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "lyy",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "yxj",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "xyd",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "hy",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "wxy",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "snzg",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "snsj",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "dnzp",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "njshkx",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "mgsx",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "dxsw",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
  {
    id: "dy",
    name: "（待确认）",
    birth: "",
    death: "",
    summary: "（待补充）",
    biography: "（待补充）",
    period: "建团初期",
    importance: 3,
    tags: [],
  },
].map((c) => ({
  ...c,
  image: restoredImage(c.id),
  original: `/inputs/inputsF/${c.id}.jpg`,
}));
